 import { NextResponse } from 'next/server';

  export async function POST(req: Request) {
    try {
      const { prompt } = await req.json();
      const apiKey = process.env.GROQ_API_KEY;

      if (!apiKey) {
        return NextResponse.json({ error: "API Key missing" }, { status: 500 });
      }

      const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "qwen/qwen3.8-27b", // আপনারপাঠালিস্টথে সঠিকমডেল
          messages: [
            {
              role: "system",
              content: `You are a multilingual SEO expert.
              1. Detect the language of the user's prompt (English, Bengali, Banglish, etc.).
              2. Generate 3 high-converting Meta Titles and Meta Descriptions in that SAME language.
              3. Return ONLY a valid JSON array of objects. Format: [{"title": "...", "description":
  "..."}, {"title": "...", "description": "..."}, {"title": "...", "description": "..."}]
              4. Do not add any conversational text.`
            },
            {
              role: "user",
              content: prompt
            }
          ],
          response_format: { type: "json_object" },
        }),
      });

      if (!response.ok) {
        const text = await response.text();
        console.error("Groq API Error:", text);
        return NextResponse.json({ error: "API Error" }, { status: response.status });
      }

      const data = await response.json();
      const contentStr = data.choices[0].message.content;
      const parsed = JSON.parse(contentStr);

      // ডা যেফরম্যাটেইআসুক, আমরাArray অংশ খুঁজেনেবো
      let finalResults = [];
      if (Array.isArray(parsed)) {
        finalResults = parsed;
      } else if (typeof parsed === 'object') {
        const foundArray = Object.values(parsed).find(val => Array.isArray(val));
        finalResults = foundArray || [];
      }

      if (finalResults.length === 0) {
        throw new Error("No results generated by AI");
      }

      return NextResponse.json(finalResults);
    } catch (error: any) {
      console.error("Server Error:", error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }
  }